# Generated by Django 5.0.3 on 2024-03-16 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_document_id_alter_document_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='pptx/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(max_length=255, upload_to='pdfs/'),
        ),
    ]
