# Generated by Django 5.0.3 on 2024-03-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_pptx_file_alter_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
